SRC_DIR=./src
BIN_DIR=./bin
LIB_DIR=./lib
HEADER_DIR=./include

DEBUG=-g
OPT=-O2

all:leftist-tree
leftist-tree: $(SRC_DIR)/leftist-tree.cpp
	g++ $(DEBUG) $(OPT) $(SRC_DIR)/leftist-tree.cpp -o $(BIN_DIR)/leftist-tree -I$(HEADER_DIR)


